// Generated by dojo-bindgen on Thu, 22 Aug 2024 20:04:33 +0000. Do not modify this file manually.
import { DojoProvider } from "@dojoengine/core";
import { Account } from "starknet";

export type IClient = Awaited<ReturnType<typeof client>>;

export function client(provider: DojoProvider) {
    // System definitions for `rugged` contract
    function rugged() {
        const contract_name = "rugged";

        // Call the `initialize_platform_fees` system
        const initializePlatformFees = async (props: { account: Account; feePercentage: number }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "initialize_platform_fees",
                        calldata: [props.feePercentage],
                    },
                    "dojo_starter"
                );
            } catch (error) {
                console.error("Error executing initialize_platform_fees:", error);
                throw error;
            }
        };

        // Call the `play_game` system
        const playGame = async (props: { account: Account; betAmount: bigint }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "play_game",
                        calldata: [props.betAmount.toString()],
                    },
                    "dojo_starter"
                );
            } catch (error) {
                console.error("Error executing play_game:", error);
                throw error;
            }
        };

        return {
            initializePlatformFees,
            playGame,
        };
    }

    return {
        rugged: rugged(),
    };
}