// Generated by dojo-bindgen on Thu, 22 Aug 2024 20:04:33 +0000. Do not modify this file manually.
import { DojoProvider } from "@dojoengine/core";
import { Account } from "starknet";

// export type IClient = Awaited<ReturnType<typeof client>>;

export function client(provider: DojoProvider) {

    // System definitions for `rugged` contract
    function rugged() {
        const contractName = "dojo_starter-rugged";

        // Call the `initialize_platform_fees` system
        const initializePlatformFees = async (props: { account: Account; feePercentage: number }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contractName,
                        entrypoint: "initialize_platform_fees",
                        calldata: [props.feePercentage.toString()],
                    },
                    "dojo_starter-rugged"
                );
            } catch (error) {
                console.error("Error executing initialize_platform_fees:", error);
                throw error;
            }
        };

        const playGame = async (props: { account: Account }) => { 
            try {
                console.log(props.account);              
                return await provider.execute(
                    props.account,                    
                    {
                        contractName: contractName,
                        entrypoint: "play_game",
                        calldata: [], // No parameters
                    },
                    "dojo_starter-rugged"
                );
            } catch (error) {
                console.error("Error executing play_game:", error);
                throw error;
            }
        };

        return {
            initializePlatformFees,
            playGame,
        };
    }

    return {
        rugged: rugged(),
    };
}
